### ISSUE TITLE
Browser auto close

### ISSUE THREAD

**Issue by PsychicRoot** [EpicnessTwo/StreamLurker#4]
Would it be possible to add functionality to auto close the browser tab again when streamer goes offline.

**Comment by EpicnessTwo** [comment]
I'll do some looking into this but might not be possible as this doesn't actually hook into the browser in any fashion and instead calls on the OS to open the default browser.

**Comment by PsychicRoot** [comment]
Appreciated if it's possible nice. If not oh well we tried.

tors. 15. feb. 2024 17.27 skrev EpicnessTwo ***@***.***>:
